### ISSUE TITLE
Missing namespace Breezy in extensions generated files

### ISSUE THREAD

**Issue by harrison314** [Ludovicdln/Breezy#2]
I tried `Breezy.SourceGenerator`, but the generated code cannot be compiled because the namespace `Breezy` is missing in the extension methods for `DbConnection` (eg. `QueryAsync`).

Try using `Breezy.SourceGenerator` in a project where the namespace does not start with `Breezy.`.

**Comment by Ludovicdln** [comment]
sorry for that, issue fixed, thank's
